use_frameworks!

platform :ios, '10.0'

target 'YJUIExtension_Example' do
  pod 'YJUIExtension', :path => '../'

  target 'YJUIExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
